### ISSUE TITLE
Escrever a descrição do projeto  no README.md ...

### ISSUE THREAD

**Issue by chicaothiago** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#27]
## **Objetivo**

**Como** alguém olhando para o projeto  
**Quero** que no repositório tenha uma descrição coerente  
**Para** saber para que serve e o que significa o projeto

## **Contexto**

O repositório existe hoje sem nenhuma descrição do que é o ID SAÚDE

## **Escopo**

- [ ] Adicionar uma introdução ao projeto
- [ ] Como colocamos para funcionar o desenvolvimento
- [ ] Como posso contribuir
- [ ] Tecnologias envolvidas 

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** estou acessando o repositório
**Quando** estou na página inicial  
**então** tenho um readme descrevendo o projeto.

# Observações

ex: Prototipo

**Comment by chicaothiago** [comment]
Projeto de transformação digital dos serviços públicos, no que se refere à implementação do Login Único, conforme diretrizes da Plataforma de Cidadania Digital, previstas no Decreto nº 8.936/16.
Drive: https://drive.google.com/drive/folders/1_HpkwDtosElje35X0k-oaUpAdrA8lCYa

**Comment by chicaothiago** [comment]
Projeto de transformação digital dos serviços públicos, no que se refere à implementação do Login Único, conforme diretrizes da Plataforma de Cidadania Digital, previstas no Decreto nº 8.936/16.
Drive: https://drive.google.com/drive/folders/1_HpkwDtosElje35X0k-oaUpAdrA8lCYa

**Comment by marameida** [comment]
SUGESTÃO DE ESCRITA:

**Bem-vindo ao repositório do IdSaúde!**
O IDSaúde é um sistema de cadastro de Identidade Digital, usado como meio de acesso do usuário aos serviços digitais à ele integrados. Apresenta a proposta de garantir a identificação de cada cidadão que acessa os serviços dos sistemas da ESP/CE.

Com um único login e senha o usuário pode utilizar todos os serviços públicos digitais que estejam integrados com o IDSaúde. Fornece um nível de segurança compatível com o grau de exigência, natureza e criticidade dos dados e das informações pertinentes ao serviço público solicitado.

No IdSaúde se considera tanto a necessidade de estruturar um cadastro robusto que sirva para subsidiar a construção de políticas públicas eficazes de saúde, quanto o acolhimento do profissional de saúde em suas necessidades de formação e outras demandas.

Com a intenção de esclarecer o usuário sobre o IDSaúde (Identidade Unica de Saúde), são necessárias ações e espaços como este que permitam aos profissionais da ESP conhecerem o programa, facilitando sua utilização e adesão aos seus serviços.

**Quem faz?**
O IdSaúde  é uma iniciativa da Escola de Saúde Pública, compondo o quadro de projetos do Felicilab (Laboratório de Inovações para o Sistema Único de Saúde no Ceará) vinculado ao NIT (Núcleo de Inovação Tecnológica).
 
**Veja também:**
•	nosso Kanban
•	nosso Grupo no Telegram
