### ISSUE TITLE
Verificar se o botão "Esqueci minha senha" está funcionando, enviando e-mail para a usuária.

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#29]
## Verificar se a usuária está recebendo e-mail em sua caixa postal ao clicar no botão "Esqueci minha senha", para que possa continuar a recuperação da conta.

**Como** pessoa usuária do sistema  
**Quero** receber o e-mail de recuperar a senha  
**Para** que eu possa redefinir minha senha quando a esquecer

## Contexto

- Para poder recuperar sua conta, a usuária tem como única forma usar a opção "esqueci minha senha". Para isso é preciso que o sistema envie para seu e-mail cadastrado um link para criar uma nova senha. Caso isso não aconteça  fluxo para e a usuária fica sem saída.

## **Escopo**

- [x] Verificar qual ação é ativada ao clicar no botão
- [x] Ver se o SMTP está ativado e funcionando
- [x] Realizar possíveis ajustes
- [x] Testar se o e-mail é enviado normalmente

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Esqueci a senha  
**Dado que** acesso a página de recuperar a senha  
**Quando** clico no botão de esqueci a senha  
**então** receber um e-mail para redefinição da senha

# Observações

Nenhuma.

**Comment by victorMagalhaesPacheco** [comment]
@danielgula em testes interno com diversas contas foi possível receber o email e realizar a alteração. Necessário realizar o teste pessoalmente com a Clarisse.

**Comment by marameida** [comment]
@chicaothiago necessário realizar o teste pessoalmente com a Clarisse.

**Comment by victorMagalhaesPacheco** [comment]
Realizei o teste com a usuária que reportou o problema e nos testes realizados foi verificado que o EMAIL informado para recuperação de senha não existe, então jamais chegará pois o EMAIL não existe cadastrado na base de dados.

**Comment by victorMagalhaesPacheco** [comment]
Um possível problema verificado no keycloak que impacta na experiência do usuário é que mesmo o e-mail não cadastrado no keycloak e é submetido para recuperação o sistema informa uma mensagem de sucesso mesmo o e-mail não existindo na base do keycloak.

**Comment by victorMagalhaesPacheco** [comment]
https://stackoverflow.com/questions/62776327/keycloak-does-not-return-proper-message-error-for-invalid-empty-email-while-re

**Comment by Junior-Shyko** [comment]
> Um possível problema verificado no keycloak que impacta na experiência do usuário é que mesmo o e-mail não cadastrado no keycloak e é submetido para recuperação o sistema informa uma mensagem de sucesso mesmo o e-mail não existindo na base do keycloak.

Viche mais que doidera!

**Comment by victorMagalhaesPacheco** [comment]
Com o e-mail cadastrado e solicitado constando no IDSaude a seguinte mensagem com a recuperação
![email-senha](https://user-images.githubusercontent.com/3487411/109171973-0be4a900-7761-11eb-8b3f-44ea2e96e8e3.jpeg)
