### ISSUE TITLE
Analisar migração do keycloak para versão v12 em produção.

### ISSUE THREAD

**Issue by chicaothiago** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#31]
## **Objetivo**

**Como** desenvolvedora  
**Quero** verificar se é possível implantar o idsaúde com o keycloak na versão 12  
**Para** manter sempre atualizado as versões do keycloak

## **Contexto**

A versão atual em produção está no servidor de homologação e está com a versão 11.0.2. É desejado por em produção com a versão 12 do keycloak para manter o sistema atualizado e com as mais novas funcionalidades.

## **Escopo**

- [ ] Atualizar a versão do keycloak para a 12
- [ ] Migrar os clientes e os dados do keycloak da v11 para a v12 (homolog para produção)

## **Fora de Escopo**

- Implementar uma solução de migração de informação e dado

## **Critérios de Aceitação**

- [ ] Acessar o idsaúde e está na versão 12  
**Dado que** acesso o idsaude  
**Quando** clico nas informação do sistema  
**então** exibir a versão 12 como a versão instalada

- [ ] Pessoas cadastradas migradas  
**Dado que** a página de usuários  
**Quando** clico em visualizar todos os usuários  
**então** exibir os usuários cadastrados

# Observações

ex: Prototipo

**Comment by chicaothiago** [comment]
Está semana foi analisada diferentes formas de migração e foi concluído que não é possível migrar e que não valia a pena.
Os motivos:

1. O Keycloak não possui uma ferramenta de migração de dados das pessoas cadastradas de uma versão para a outra. 
2. É possível exportar as configurações dos realms, um por um, e usá-los para recriar os reals, mas isto não exporta as pessoas usuárias.
3. A tentativa de fazer import somente das pessoas cadastradas não funcionou, quando se tentava visualizar os dados daquele usuário dava erro. 
4. Foi constatado um BUG na versão v12 que se você alterar o nome do realm, todo o realm quebra
5. Foi constatado um problema que se deletar o client do real no keycloak o keycloak inteiro quebra
6. Foi encontrada uma nova tabela no banco na versão 12 relacionada aos realms, podendo assim quebrar o sistema.

**Comment by jacsonp** [comment]
Segundo: https://www.keycloak.org/docs/latest/upgrading/ o ideal para realizar essa tarefa é copiar (via migração de arquivos de banco de dados) na versão atual e daí fazer a atualização via upgrade

**Comment by chicaothiago** [comment]
> Segundo: https://www.keycloak.org/docs/latest/upgrading/ o ideal para realizar essa tarefa é copiar (via migração de arquivos de banco de dados) na versão atual e daí fazer a atualização via upgrade

Isso funciona melhor se vocês tiver uma instalação local. No nosso caso que é docker, e em outro servidor, a instalação é completa e do zero.

O caso relatado é na tentativa de importação do dado do serviço antigo. O que ocasiona alguns erros.  
A tentativa de migração até o momento não foi feita as cegas. E por sinal, minha instância local continha alguns casos de uso que comentei que podem ocasionar problemas num futuro.

O que faz a versão 11 ser mais estável de se usar que a versão 12.

Sem falar que de acordo com o changelog de atualização, praticamente só a versão do template engine que atualizou. O que na real não impacta no uso da versão 11. E trouxe um bug que pode quebrar toda a aplicação.
