### ISSUE TITLE
Dailies Brainstorm

### ISSUE THREAD

**Issue by chicaothiago** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#32]

**Comment by marameida** [comment]
OBJETIVO PRINCIPAL: Fazer integração de todos os sistemas da ESP com o IDSaúde

COMO: 
1º Conhecer o IDSaúde;
2º Conhecer os demais programas  (ISUS, Mapas, Seleções, RPES, Rescovid, MOODLE);
3º Levantar as informações necessárias de cada programa para cadastro do usuário;
4º Elaborar planilha com informações coletadas;
OBS 1. Moodle - necessidade de inclusão de dados pelo usuário. Ver com o pessoal do UX melhores formas de comunicação.
OBS 2. Os demais programas que irão se adaptar ao ID Saúde. Não haverá mudança de código nele.

SUGESTÃO DE CARDS: 
- Integrar todos os sistemas da ESP ao IDSaúde;
- Reconhecimento dos programas e levantamento de informações para integração;

**Comment by uira** [comment]
@marameida Não esqueçam do WordPress, pois teremos cada vez mais pequenos sites com ele, precisando de autenticação

**Comment by marameida** [comment]
- Acompanhamento do card no ISUS referente à adequação de integração entre ISUS e o IDSaúde. #34
- Início do desenvolvimento das correções da Autenticação no ISUS. #34 
- Agendar com o DesignLab a análise da experiência do usuário ao acessar o MOODLE (espvirtual) através do IDSaúde. (Construção de Fluxograma)
        - Teste de mudança no design de tela (fricção na jornada do usuário).

**Comment by marameida** [comment]
1. Integração entre IDSaude e Moodle
Reunião com DesignLab (Daniel) sobre sugestões de testes de mudança no design de tela  - 29/01/21
  - Incluir caixa de direcionamento para página do IDSaúde
        - "Você já é cadastrado no ID Saúde" - redirecionar para página de acesso do IDSaúde
        - "Caso não possua cadastro" - redirecionar para página de cadastro do ID Saúde
  - Após primeiro acesso manter mensagem: " você está acessando esse site por meio de sua senha e usuário do IDSaúde"...
  
2. Campanha de Comunicação do ID Saúde 
   - Identidade Digital
   - Sugestão: pesquisa com os usuários

**Comment by victorMagalhaesPacheco** [comment]
> 1. Integração entre IDSaude e Moodle
>    Reunião com DesignLab (Daniel) sobre sugestões de testes de mudança no design de tela  - 29/01/21
> 
> * Incluir caixa de direcionamento para página do IDSaúde
>   - "Você já é cadastrado no ID Saúde" - redirecionar para página de acesso do IDSaúde
>   - "Caso não possua cadastro" - redirecionar para página de cadastro do ID Saúde
> * Após primeiro acesso manter mensagem: " você está acessando esse site por meio de sua senha e usuário do IDSaúde"...
> 
> 1. Campanha de Comunicação do ID Saúde
>    
>    * Identidade Digital
>    * Sugestão: pesquisa com os usuários

Referente a caixa de direcionamento para página do IDSaúde, sugiro usar o mesmo fluxo do https://sso.acesso.gov.br onde ao digitar o CPF o sistema verifica se existe cadastro ou não.

**Comment by marameida** [comment]
Daily 02/02/21
- Retorno Victor
- Repasses sobre pendencias atuais
    1. Integração demais programas (MOODLE e ISUS - em andamento)
    2. Para evitar duplicidade no CPF : 
       -  Sugestão: login com email e CPF cadastrados;
    3. Atividade em Backlog: retorno ao usuário com email próprio, evitando uso do "gmail"

**Comment by victorMagalhaesPacheco** [comment]
Em análise da mudança do processo de autenticação do IDSaúde para atender outros sistemas como o (moodle) que hoje está pelo email definido no escopo do projeto inicialmente. Baseado na necessidade no eventual update  no CPF (username) do keycloak, as seguintes possíveis atualizações analisadas.

1) (IDSaúde) Acessar keycloak e ir em configurações do realm e acessar login e definir email as username como false
2) (API iSUS) Ir na API do iSUS e mudar no arquivo UserKeycloak.php para passar o CPF 'username' => $this->cpf no método toKeycloak
3) (API iSUS) Realizar mudança na API do iSUS para alterar o campo "email" para "emailoucpf" onde o acesso pode ser por email ou cpf pelo keycloak
4) (APP iSUS) Realizar mudança no front do aplicativo para autenticação por email e CPF
5) (Indefinido - api isus) Realizar um script de migração do atributo do Usuário CPF em Attributes e migrar para "username"
6) (IDSaúde tema) - Realizar Mudança no Tema para trocar a Label username para CPF (identificador único) em todo o tema da Saúde

Observação necessário adicionar no backlog e em seguida realizar o refinamento em cada repositório especificado no item.

**Comment by marameida** [comment]
Daily 04/02/2021
**Anaĺise do Board**
1. Implementar mudança de remetente de e-mail - Encaminhado para Daniel Goulart.
2. Ajustes na integração ISUS e IDSaúde - sendo realizados.
3. Email de devolutiva sobre informações aos usuários do ID Saúde - sugestão de mudança para não ser gmail - Ação bloqueada temporariamente.
4. Acesso facebook e Google - refinamento de cards
5. Campanha de Comunicação 
     - Sugestões: Conversar com a Clarisse
     - Ver modelo gov.br (login único do governo federal)
     
**Elaboração de apresentação para alinhamento gerencial**

**Comment by marameida** [comment]
Daily 08/02/2021
**Anaĺise do Board**

1. Atividade "Esqueci minha senha" ajustada e movida para coluna "Concluídas/produção"
2. Integração ISUS e IDSaúde: realização de testes e processo de finalização
3. Campanha de comunicação  com usuários: 
     - Levantamento de informações
     - Agendamento de reunião com Publicilab

**Comment by marameida** [comment]
Daily 10/02

**Análise Board**
1. Pendencias @marameida : 
   - Escrita IDSaúde Read.md (Objetivo, metas e Definição);
   - Conversar com pessoal que está gerenciando contas facebook e google;
   - Fechar análise gerencial semanal;
   - Priorizar adequação do termo de uso no IDSaúde;
   - Seguir com Campanha de Comunicação com usuário;
 2. Ajuste na Integração ID Saúde e ISUS @chicaothiago  
 3. Pilotos inserção CPF no login do IDSaúde @victorMagalhaesPacheco 
 
**Reunião com Publicilab**
- Conversa com Uirá sobre Identidade e objetivo principal do IDSaúde;
- Pensar em estratégias de divulgação;
- Sugestão: dúvidas frequentes dentro da página do IDSaúde;

**Comment by marameida** [comment]
**Resumo de Pendencias 15/02**

- Desenvolver Cards Épicos;
- Adequar ID Saúde à LGPD (marcar com Danilo);
- Ajustar URL do IDSaúde;
- Atualizar SPRINT;
- Prosseguir com escrita do ID Saúde;
- Integração IDSaúde e gov.br

**Comment by marameida** [comment]
**Daily 23/02**
Acolhida Marcelo
Reconhecimento GitHub/Board

PENDENCIAS: 
- Atualização do Termo de uso/Regulação LGPD
- Escrita ID Saúde/Reconhecimento do usuário
- Ajuste email Clarisse
- Ajuste integração ID Saúde- ISUS
- Inclusão CPF 
- Integração ID Saúde/Moodle

**Comment by marameida** [comment]
Daily 26/02/21

- Repriorizar atividades (planning): agendada para 01/03 às 14:30;
- Atividade "esqueci minha senha" gerou novo card (necessário refinamento);
- Atenção: finalização de ajuste na integração do ISUS com IDSaúde (fase mudança de rotas);
