### ISSUE TITLE
Customizar tema Saúde username para CPF

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#45]
## **Objetivo**

**Como** usuária do ID Saúde  
**Quero** acessar o ID Saúde depois da autenticação realizada pelo CPF ou EMAIL  
**Para** acessar os recursos internos da minha conta

## **Contexto**

- Atualmente o ID Saúde a forma de autenticação está sendo feita apenas pelo e-mail e internamente no tema as referências são usadas USERNAME. Necessário atualizar as referências em (cadastro, login, minha conta, documentos) de USERNAME para CPF. 

## **Escopo**

- [x] Acessar a área administrativa do keycloak como super usuário e em seguida desabilitar a opção "Email as username".
- [x] As configurações de alterações das nomenclaturas no tema ficam em um arquivo chamado "/base/account/messages/messages_pt_BR.properties" que está localizado dentro do CONTAINER do KEYCLOAK, necessário adicionar o mesmo arquivo em "/saude/account/messages/" como o mesmo nome "messages_pt_BR.properties". 
- [x] No Arquivo novo criado em "/saude/account/messages/" com nome "messages_pt_BR.properties" é necessário mudar todas as referências de USERNAME para CPF
- [x] Realizar o processo de validação do CPF em novo cadastro de um usuário
- [x] Adicionar máscara no campo de CPF usando o seguinte padrão: (###.###.###-##)

## **Fora de Escopo**

- Não se aplica

## **Critérios de Aceitação**

- [x] Desabilitar a opção "Email as username" nas configurações do REALM
**Dado que** acesso o id Saúde como usuário administrador do REALM
**Quando**  acesso as configurações do REALM em login
**então** a opção de "Email as username" estará desabilitada

- [x] Alterar nomenclatura USERNAME para CPF
**Dado que** acesso a área do usuário no IDSaude
**Quando**  acesso qualquer página como por exemplo: cadastro, login, minha conta, documentos
**então** onde existia a nomenclatura USERNAME passará a existir CPF

- [x] Realizar o processo de validação do CPF no ato do cadastro
**Dado que** acesso a página de cadastro "Novo Registro"
**Quando**  preencho o CPF inválido e aparece uma mensagem em vermelho abaixo do campo de CPF informando que o "CPF digitado é INVÁLIDO" e o submit do formulário fica desabilitado (disabled).
**então** Quando preencho com um CPF VÁLIDO prossigo com o preenchimento de todos os outros campos obrigatório no restante do formulário e o botão submit fica habilitado para enviar o novo cadastro.

- [x] Realizar login com CPF
**Dado que** acesso a página de login do IDSaude
**Quando**  preencho com CPF e senha
**então** Então é realizado a validação nos campos informados no formulário (CPF e SENHA)

- [x] Realizar login com EMAIL
**Dado que** acesso a página de login do IDSaude
**Quando**  preencho com EMAIL e senha
**então** Então é realizado a validação nos campos informados no formulário (EMAIL e SENHA)

# Observações

Na alteração de nomenclatura do arquivo "messages_pt_BR.properties" é necessário acessar o container através da interface gráfica do próprio docker ou através da linha de comando usando seguinte comando: 
`docker exec -it HASH_CONTAINER_ID bash`

**Comment by victorMagalhaesPacheco** [comment]
Branch alteração no tema: https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude/tree/feature/auth-cpf-email

**Comment by victorMagalhaesPacheco** [comment]
### TITULO DO MEU PROJETO

**Comment by ricardopoppi** [comment]
@marameida se conseguir acesso ao ambiente de homologação do iSUS seria legal pra gente testar essa issue
