### ISSUE TITLE
Adicionar serviço do gov.br para acessar o ID Saúde

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#50]
### Objetivo
Disponibilizar e facilitar nova forma de autenticação pelo gov.br para o ID Saúde

### Escopo
- [ ] Processo de Integração com gov.br 

### Fora de Escopo
Integração com qualquer outro serviço de autenticação

### Critérios de Aceitação
- [ ] Autenticação pelo gov.br
**Dado que** acesso ao ID Saúde
**Quando** Acesso a tela de login do ID Saúde
**então** deve aparecer um botão do gov.br para autenticação

Observação: https://sso.acesso.gov.br/login?client_id=contas.acesso.gov.br&authorization_id=177b04d0220

**Comment by RaniGub** [comment]
A tarefa será contemplada no repositório do Mapa da Saúde:
Análise da jornada de login por meio do gov.br #691
