### ISSUE TITLE
Adequação de texto sobre "termos de uso" para regulação com LGPD.

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#56]
## **Objetivo**

**Como** usuário do ID Saúde  
**Quero** adequar texto sobre termos de uso 
**Para**auxiliar na regulação do ID Saúde à LGPD.

## **Contexto**

- Os usuários do ID Saúde se cadastram no sistema, mas ainda não preenchem os termos de uso, necessários para adequação à LGPD.

## **Escopo**

- [x] Adequar texto sobre "termos de uso"
- [ ] Criar tela para preenchimento e aceite dos mesmos pelo usuário;
- [ ] Encaminhar para link com maiores detalhes sobre a política de adequação e proteção dos dados. 

## **Fora de Escopo**

- Evitar que o usuário desconheça sobre a utilização dos seus dados fornecidos.
## **Critérios de Aceitação**

- [ ] Adequação de texto sobre termos de uso dos dados 
**Dado que** permitirá autorização do usuário no uso de seus dados.
**Quando**  o mesmo preencher ciência sobre os termos de uso
**então** o usuário conhecerá o destino de suas informações fornecidas.

# Observações

Não se aplica

**Comment by marameida** [comment]
Adequação de texto sobre "termos de uso" para ID Saúde com objetivo de iniciar adequação do programa à LGPD.
https://drive.google.com/file/d/1HjVVyXfEG_hGOGssBkkEBH0Y9Wgytz2W/view?usp=sharing

**Comment by thaistoscano** [comment]
Atividade será tomada e processos resgatados. Em levantamento com Flaviane dos processos jurídicos já aprovados.

**Comment by daianeabreu** [comment]
Encontramos o processo de número 06102723/2020 arquivado em nosso setor. Conversei com o Antônio Edson e ele sugeriu o desmembramento desse processo já que o mesmo trata de quatro temas específicos: "Termo e condições de Uso do iSUS, Termo e Condições de Uso do Mapa da Saúde, Termo e Condições de Uso do ID Saúde e Política de Privacidade da ESP."

**Comment by marameida** [comment]
Ciente. Estaremos retomando essa atividade pelo ID Saúde também.

**Comment by marameida** [comment]
Conforme atualização com Daiane:
- A Política de privacidade da Esp foi criada, estando na fase de aprovação final pela Superintendência. O documento foi desenvolvido com base nas diretrizes da LGPD. Além disso está sendo criado o Termo de Uso do Id Saúde, Isus e Mapa da Saúde. Foi recebido um parecer do Jurídico sobre necessidade de alterações, que ainda serão realizadas.  nos termos já criados.

**Comment by ricardopoppi** [comment]
Plano de ação para isso:

- [ ] Disparar uma issue de designlab para formular a jornada ux e telas para a aceitação de política de privacidade no id saúde e o reflexo da política e termos com links nas três soluções (id saúde, isus, mapas)
- [ ] Quando telas prontas, disparar issues de desenvolvimento para cada produto
- [ ] Quando em homologação, demandar a versão mais atual da política e termos e caso ainda não tenha sido concluída publicar nos apps a versão provisória

**Comment by marameida** [comment]
Feito pareamento junto a Daiane (@daianefreira). Ainda na fase de ajustes nos termos de uso, de acordo com solicitações do jurídico, principalmente quanto às informações específicas da TI Fernando e João estão responsáveis por isso. 

Sugerimos a formação de um GRUPO DE TRABALHO (@ricardopoppi e Joao Capistrano) para acompanhar os encaminhamentos futuros referentes à LGPD, incluindo demais produtos envolvidos.
