### ISSUE TITLE
Mapear experiência do usuário para o id Saúde (Keycloak)

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#60]
A ferramenta do Keycloak possui temas que podem ser atualizados, podendo alterar o visual, imagens e elementos da interface.
Contudo, é necessário apoio de desenvolvedores para criar uma build da solução e jogar para a produção.
Esta tarefa é para mapear as telas do Keycloak e definir a experiência do usuário. 
Falta fazer
- [x] Login
- [x] Cadastre-se
- [x] Esqueceu a senha
- [x] Editar usuário
- [x] Área do usuário

**Comment by RaniGub** [comment]
Tarefa vinculada à Iniciativa #80, Épico do Fluxo de Cadastro (Card ainda não criado)

**Comment by RaniGub** [comment]
Escopo da tarefa precisa ser refinado.

**Comment by RaniGub** [comment]
https://www.figma.com/file/VUKgRchg1ioP2dNM0aWu7g/ID-Sa%C3%BAde?node-id=0%3A1
