### ISSUE TITLE
Revisar e coordenar assinaturas do plano de integração gov.br

### ISSUE THREAD

**Issue by ricardopoppi** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#74]

**Comment by ricardopoppi** [comment]
Documento pronto e revisado.

Próximos passos

- [ ] @victorMagalhaesPacheco carrega o pdf no assinador - https://assinador.iti.br/ - usando a conta gov.br e assina
- [ ] @uira recebe o documento assinado e faz o mesmo procedimento, assinando pelo assinador com sua conta gov.br
- [ ] @victorMagalhaesPacheco gera sua chave pública PGP
- [ ] @uira gera sua chave pública PGP
- [ ] @ricardopoppi envia o documento e as chaves para o email da integração integracao-acesso-govbr@economia.gov.br com o assunto "CHAVE DO AMBIENTE ID Saúde – Escola de Saúde Pública do Ceará Paulo Marcelo Martins Rodrigues – ESP – CE"
- [ ] @victorMagalhaesPacheco e @uira vão receber as credenciais de teste nos seus emails
- [ ] Execução do cronograma
- [ ] Envio da comprovação dos testes para o email da integração para receber as credenciais de produção

**Comment by ricardopoppi** [comment]
Instruções para referencia:

A chave pública PGP deverá ser gerada pelo Representante Legal do órgão ou entidade dona do serviço a ser integrado, e Representante Técnico. Ambos devem constar na tabela do item 3. Existem algumas orientações para administração da chave pública PGP no Roteiro de Integração do Login Único (https://manual-roteiro-integracao-login-unico.servicos.gov.br/pt/stable/chavepgp.html); 

O documento e chave deverão ser encaminhados para e-mail: integracao-acesso-govbr@economia.gov.br

Com recebimento do documento e da chave pública PGP, todos com correta completude das informações, a credencial de teste ou produção será gerada e encaminhada aos e-mails dos representantes descritos na tabela do item 3 deste documento.

O Assunto do e-mail de liberação de chaves terá o padrão: CHAVE DO AMBIENTE [nome do ambiente] – [Nome do Órgão/Entidade] – UF

A chave de produção somente será emitida após comprovação da integração com sucesso ao ambiente de TESTE. Para fins de comprovação, deve ser encaminhado para o e-mail: integracao-acesso-govbr@economia.gov.br, vídeo da integração em funcionamento, junto com o Plano de Integração preenchido com as URLs do ambiente de produção do órgão/entidade e chave pública PGP do Órgão/Entidade. ***ATENÇÃO: No ambiente de PRODUÇÃO SOMENTE SÃO PERMITIDAS URLS em HTTPS.

O prazo para envio da credencial é de até 72hrs.

O Órgão/Entidade DEVE avisar (via e-mail para integracao-acesso-govbr@economia.gov.br) ao Ministério da Economia assim que a integração no ambiente de produção for concluída e estiver disponível para a sociedade.

**Comment by ricardopoppi** [comment]
email enviado para o governo federal. @uira e @victorMagalhaesPacheco devem receber a credencial de teste nos seus emails, com conteúdo criptografado via a chave pública PGP fornecida

**Comment by ricardopoppi** [comment]
credenciais de teste desincriptadas enviadas para @lucaspq para implementação do teste

**Comment by lucaspq** [comment]
@ricardopoppi no ambiente de HML já podemos iniciar os testes com o login GovBR. Estou fazendo testes também alterando alguns parâmetros do Keycloak.

https://dev.id.org.br/auth/realms/saude/account/

O padrão para responder as perguntas no cadastro Gov.BR:
-Nome da mãe: MAMAE
-Data de Nascimento : 01/01/1980

**Comment by ricardopoppi** [comment]
@lucaspq fiz os testes e consegui fazer a integração. quando o usuário já tem uma conta gov.br retorna direitinho para o id saúde.

porém, quando o usuário precisar criar uma conta nova, ele retorna para a tela de login do id saúde novamente (print 1) sendo que jornada ideal seria concluir o processo de autorização do id saúde no gov.br e retornar para a tela de complementação de cadastro para concluir (print 2).

pode ser alguma limitação do gov.br mas de qq forma vale checar

PRINT 1
![screenshot-dev id org br-2022 06 03-19_04_40](https://user-images.githubusercontent.com/1162183/171960653-26122902-d68b-4a29-bbbb-0b7d35e3de4b.png)


PRINT 2
![screenshot-dev id org br-2022 06 03-19_08_05](https://user-images.githubusercontent.com/1162183/171960665-a5274fff-84e1-4403-be39-c829e9dd5427.png)
