### ISSUE TITLE
Bug de integração do id saúde com o mapas

### ISSUE THREAD

**Issue by ricardopoppi** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#79]

**Comment by ricardopoppi** [comment]
Quando usuário não logado acessa uma oportunidade no mapas e vai fazer login no id, ele não é redirecionado de volta à url do mapas de onde ele partiu

**Comment by marameida** [comment]
Confirmado que o bug se replica no ISUS também. Equipe ciente. Solicitado acesso ao ambiente de homologação para ajustes. Gratos pelo repasse @luannaalves @thaistoscano @Laysacunha.

**Comment by ricardopoppi** [comment]
Testes feitos no mapas em homologação e não foi possível replicar. Ao entrar em uma oportunidade sem estar logado, tanto o cadastro quanto o login via id saúde retornam para a mesma oportunidade sem problemas identificados.

Fechando essa issue.

**Comment by ricardopoppi** [comment]
Se alguém quiser tentar replicar, criei essa oportunidade para teste em homologação: https://mapadasaude.dev.org.br/oportunidade/562/
