### ISSUE TITLE
Resolver problema de recuperar senha com CPF

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#88]
## **Contexto**

A recuperação de senha com CPF pelo IdSaude não está funcionando devido a atualização no MAPA que inseriu a máscara no CPF. O Victor resolveu momentaneamente o problema em produção, mas precisar ser melhorado o processo.  

## **Critérios de Aceitação**

- [x] Corrigir a recuperação de senha com CPF no IdSaude
**Dado que** o agente
**Quando** solicitar a recuperação de senha no IDSAUDE pelo CPF 
**então** receberá um e-mail de recuperação. 

## Observações
Links de apoio e informações adicionais

**Comment by lucaspq** [comment]
@nestorufpe favor testar solução aplicada em HML: https://dev.id.org.br/auth/realms/saude/account/

**Comment by nestorufpe** [comment]
Testei recuperar com o CPF, deu certo @lucaspq

**Comment by nestorufpe** [comment]
@lucaspq subiu para produção no dia 13/09/22 com a apoio do @JuinEsp.
